version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mock-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mock_db
      MYSQL_USER: mock_user
      MYSQL_PASSWORD: mock_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - mock-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: mock-service-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mock_db
      - SPRING_DATASOURCE_USERNAME=mock_user
      - SPRING_DATASOURCE_PASSWORD=mock_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
      - LOGGING_LEVEL_COM_KDS_MOCK=DEBUG
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mock-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  mock-network:
    driver: bridge 